### PR TITLE
Saving reprojected GeoTIFFS

### PR DESCRIPTION
**Pull request by mbjoseph**
Hey @SepidehD - this version of the notebook should be enough to get you going. I'm specifying a proj4string in my call to `gdalwarp` which does the reprojection. If you want to specify a new target projection, you can change this proj4string.

### CODE REVIEW

**Comment by SepidehD** [comment]
Hi Max,

Still the coordinate system of tif files is sinusoidal. It seems that
gdalwarp and translate cannot change the coordinate system. I have tried
many times with different lines of code, but like now, the coordinate
remains the same (sinusoidal).

Please let me know if you can help to figure this out.

Thank you for your time and attention.

Best,
Sepideh






*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by mbjoseph** [comment]
The files that end in `_projected.tif` are not in sinusoidal coordinate systems. Take a look at the notebook, where the projection information is printed for those.

**Comment by SepidehD** [comment]
Hi Max,

Thank you for your reply.

I get this error:
AttributeError: 'NoneType' object has no attribute 'GetProjection'


I tried to use the full path in gdal.open() but still I get the this error.
Is there any setting that I need to do before running r.GetProjection()?

Thank you for your attention.

Best,
Sepideh







*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by mbjoseph** [comment]
I would recommend that you debug this a bit to figure out where the problem is arising. Try to step through the operations for just one file (e.g., the first file in the `files_names` object). That will help you to figure out what is going wrong. 

That AttributeError indicates that the raster is not loading properly. Are you using `gdal.Open` or `gdal.open`? 

Can you verify that the new rasters are being created on your machine? You can check this by either looking at the date of last modification, or deleting all of the GeoTIFFS and running the script again to see which do or do not get created. 

There are no additional settings that you need for this to run. The Jupyter Notebook that I sent contains everything that I did to get this going.

**Comment by SepidehD** [comment]
I can create Gtiff files with no problem. The error is when I run the
r=gdal.Open.
when I print "r" it shows null, that means gdal.Open() doesnt work.

I am looking at this website: http://www.gdal.org/gdal_tutorial.html
It seems  python automatically installs  GDALAllRegister()
<http://www.gdal.org/gdal_8h.html#a9d40bc998bd6ed07ccde96028e85ae26>  that
is required for gdal.Open but I dont know why I still have problem using
gdal.Open().

Please let me know if you have any suggestion.

Thank you,
Sepideh


*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by mbjoseph** [comment]
Sounds like something may be wrong with your GDAL installation. Are there any error messages that are printed to your terminal when you run gdal.Open? 

If your GDAL installation is messed up, it may be worth trying a new conda environment with just GDAL and jupyter installed.

I used the Earth Lab spatial python Docker image to do the processing, because I find that GDAL installation issues can be extremely tricky. If you want to use it, there are instructions here: https://hub.docker.com/r/earthlab/spatial-python/

**Comment by SepidehD** [comment]
Hi Max,

I dont think the problem is related to gdal, since I am using gdal in other
notebooks,
Also, I am using python 2.7 so I cannot update based on the docker that you
have provided.

I am trying debugging line by line. It seems there is a small problem
related to the direction of the folder. Because when I print r it is null.

I will be thankful if you could look at the code and let me know what is
the problem with the gdal.Open() in the last line of the code. (The first
one works!)

Best,
Sepideh









*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by mbjoseph** [comment]
Here are some ideas: 

1. Maybe the file does not exist, or the path is wrong. You can see whether this is the case by: 

At the top of your script: 

```
import os.path
```

Then, before the second call to `gdal.Open()`:

```
os.path.isfile(new_file) 
```

If this returns `False`, then the file does not exist, or the path to the file is messed up. If it returns `True`, then the file exists, and the path is not the problem. Can you try this and let me know what you see?

**Comment by SepidehD** [comment]
I added os.path.

Could you please tell me why I get error when I define new_file?

new_file= r_data_dir + "/" + year +"/"+ b +"_proj.tif"


I want to use new_file in the reproj_cmd but I get following error:

reproj_cmd = "gdalwarp -t_srs '+proj=aea +lat_1=29.5 +lat_2=45.5
+lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m
+no_defs ' " + dset + " " + new_file

ERROR:
`SampleHDFData/2010/2010001_h10v05_proj.tif' does not exist in the file
system, and is not recognised as a supported dataset name.


Actually, it should it be exist. I want to save the final converted tif
with this name and in this address.

I dont know why you can run the same code without problem, but I cannot run
it on my laptop.

Thank you.
Sepideh




*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Pull request merged**
